development:
  adapter: redis
  url: redis://redistogo:0729f84a9a0729b936ca4cb892@hoki.redistogo.com:9247/

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:0729f84a9a0729b936ca4cb892@hoki.redistogo.com:9247/
  channel_prefix: api_production
